import React, { useState } from 'react';
import {
  Button,
  Typography,
  Avatar,
  Space,
  Row,
  Col,
  Form,
  Input,
  InputNumber,
  Select,
  DatePicker,
  Collapse,
  Modal,
  Alert,
  Tag,
  Divider,
} from 'antd';
import {
  ContainerOutlined,
  PlusOutlined,
  CopyOutlined,
  ImportOutlined,
  DeleteOutlined,
  CaretDownOutlined,
  EditOutlined,
  CloseOutlined,
  CalendarOutlined,
} from '@ant-design/icons';

const { Title, Text, Link } = Typography;
const { Option } = Select;
const { Panel } = Collapse;

const FormDocumentation = ({ t }) => {
    const [isModalVisible, setIsModalVisible] = useState(false);
    const [form] = Form.useForm();
    const showModal = () => setIsModalVisible(true);
    const handleCancel = () => setIsModalVisible(false);
    const onFinish = (values) => {
        console.log('Form Values:', values);
        setIsModalVisible(false);
        Modal.success({ title: 'Order Created!', content: 'The new agriculture order has been successfully submitted.' });
    };
    const handleCreate = () => form.submit();

    return (
        <>
            <Button type="primary" onClick={showModal}>{t.launchForm}</Button>
            <Modal
                open={isModalVisible}
                onCancel={handleCancel}
                width={960}
                closable={false}
                title={null}
                footer={null}
                styles={{
                    body: { padding: 0 },
                    content: { padding: 0 }
                }}
            >
                <div style={{ background: 'linear-gradient(90deg, rgba(79, 161, 71, 0.10) 0%, rgba(69, 99, 191, 0.10) 100%)', padding: '16px 24px' }}>
                    <Row justify="space-between" align="middle">
                        <Col>
                            <Space align="center" size="middle">
                                <Avatar shape="square" size={48} style={{ backgroundColor: '#27ae60' }} icon={<ContainerOutlined />} />
                                <div>
                                    <Title level={4} style={{ margin: 0 }}>{t.createOrderTitle}</Title>
                                    <Text type="secondary">{t.createOrderSubtitle}</Text>
                                </div>
                            </Space>
                        </Col>
                        {/* The language switcher is removed from here and is now only in App.js */}
                        <Col>
                            <Button type="text" icon={<CloseOutlined />} onClick={handleCancel} />
                        </Col>
                    </Row>
                </div>
                <div style={{ padding: '24px', background: '#FFFFFF', maxHeight: '65vh', overflowY: 'auto' }}>
                    <Form form={form} layout="vertical" onFinish={onFinish} initialValues={{ items: [{ product: 'Soybeans - Premium Grade', quantity: 1000 }] }}>
                        <Row gutter={24}>
                            <Col span={8}><Form.Item label={t.orderNumber}><Input value={t.autoGenerated} disabled /></Form.Item></Col>
                            <Col span={8}><Form.Item name="customer" label={t.customer} rules={[{ required: true }]}><Select placeholder={t.pleaseSelect}><Option value="cust1">Customer A</Option></Select></Form.Item></Col>
                            <Col span={8}><Form.Item name="plannedDeliveryDate" label={t.plannedDelivery} rules={[{ required: true }]}><DatePicker style={{ width: '100%' }} placeholder={t.selectDate} /></Form.Item></Col>
                            <Col span={8}><Form.Item name="deliveryPurpose" label={t.deliveryPurpose} rules={[{ required: true }]}><Select placeholder={t.selectPurpose}><Option value="comm">Commercial</Option></Select></Form.Item></Col>
                            <Col span={5}><Form.Item name="orderRemarks" label={t.orderRemarks}><Select placeholder={t.pleaseSelect} suffixIcon={<EditOutlined />}><Option value="1">Remark 1</Option></Select></Form.Item></Col>
                            <Col span={5}><Form.Item name="priorityLevel" label={t.priorityLevel}><Select defaultValue="normal"><Option value="normal">Normal Priority</Option></Select></Form.Item></Col>
                            <Col span={6}><Form.Item name="farmLocation" label={t.farmLocation} rules={[{ required: true }]}><Select placeholder={t.selectFarm}><Option value="loc1">Farm Location 1</Option></Select></Form.Item></Col>
                        </Row>
                        <Alert type="info" message={<Row justify="space-between"><Col>{t.expandInstructions}</Col><Col><Link style={{marginRight: 8}}>{t.expandAll}</Link><Link>{t.collapseAll}</Link></Col></Row>} style={{marginBottom: 16}} />
                        <Collapse bordered={false} defaultActiveKey={['1']} style={{ background: 'transparent' }}>
                            <Panel 
                                key="1" 
                                showArrow={false} 
                                style={{ background: '#fff', border: '1px solid #d9d9d9', borderRadius: 4, marginBottom: 16 }} 
                                header={
                                    <Row justify="space-between" align="middle" style={{width: '100%'}}>
                                        <Col>
                                            <Space align="center">
                                                <Avatar size={24} style={{ backgroundColor: '#27ae60', color: '#fff' }}>2</Avatar>
                                                <Tag style={{background: '#fff', border: '1px solid #d9d9d9'}}>{t.complete}</Tag>
                                                <Tag color="blue" icon={<CalendarOutlined />} style={{border: '1px solid #91d5ff'}}>{t.seasonal}</Tag>
                                            </Space>
                                        </Col>
                                        <Col>
                                            <Space>
                                                <Text strong>$2500.00</Text>
                                                <Button type="text" danger icon={<DeleteOutlined />} />
                                                <CaretDownOutlined />
                                            </Space>
                                        </Col>
                                    </Row>
                                }
                            >
                                <Divider style={{margin: '0 0 16px 0'}}/>
                                <Form.List name="items">{(fields) => (<>{fields.map(({ key, name, ...restField }) => (<div key={key}><Form.Item {...restField} name={[name, 'product']} label={t.agriculturalProduct} rules={[{ required: true }]}><Select placeholder={t.pleaseSelect}><Option value="Soybeans - Premium Grade">Soybeans - Premium Grade</Option></Select></Form.Item><Form.Item {...restField} name={[name, 'quantity']} label={t.plannedQuantity} rules={[{ required: true }]}><InputNumber placeholder="1000" style={{ width: '100%' }} addonAfter="Kg" /></Form.Item></div>))}</>)}</Form.List>
                            </Panel>
                        </Collapse>
                    </Form>
                </div>
                <div style={{ padding: '16px 24px', background: '#F9FAFB', borderTop: '1px solid #f0f0f0' }}>
                    <Row justify="space-between" align="top">
                        <Col>
                            <Space align="start">
                                <Text>{t.items}: 3</Text>
                                <Text>{t.completed}: 3</Text>
                                <Text>{t.priority}: Normal</Text>
                                <Text strong>{t.total}: $25000.00</Text>
                            </Space>
                        </Col>
                        <Col>
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: '8px' }}>
                                <Space>
                                    <Button icon={<CopyOutlined />}>{t.copyTemplate}</Button>
                                    <Button icon={<ImportOutlined />}>{t.importCSV}</Button>
                                </Space>
                                <Space>
                                    <Button onClick={handleCancel}>{t.cancel}</Button>
                                    <Button type="primary" onClick={handleCreate}>{t.createOrder}</Button>
                                </Space>
                            </div>
                        </Col>
                    </Row>
                </div>
            </Modal>
        </>
    );
};

export default FormDocumentation;
